#!/bin/bash
set -ex

function main() {
	if [[ "$#" -ne 3 ]]; then
		echo "Usage add-article article-name link-to-article repo"
		exit 1
	fi
	local articleName=$1
	local articleLink=$2
	local articleRepo=$3

	if ! [[ -d "${articleRepo}" ]]; then
		echo "Repo ${articleRepo} does not exist."
		exit 1
	fi

	local articlePath="${PWD}/${articleRepo}/articles/${articleName}.pdf"
	curl "${articleLink}" -o "${articlePath}"
	echo "${articleLink} downloaded to ${articlePath}"
	
}

main "$@"